/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CalculatorJNI */

#ifndef _Included_CalculatorJNI
#define _Included_CalculatorJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CalculatorJNI
 * Method:    addition
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_CalculatorJNI_addition
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     CalculatorJNI
 * Method:    substraction
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_CalculatorJNI_substraction
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     CalculatorJNI
 * Method:    multiplication
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_CalculatorJNI_multiplication
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     CalculatorJNI
 * Method:    division
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_CalculatorJNI_division
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
